CREATE TABLE `ec_user` (
	`id` INT ( 11 ) NOT NULL AUTO_INCREMENT,
	`username` VARCHAR ( 20 ) NOT NULL DEFAULT '' COMMENT '用户名',
	`nickname` VARCHAR ( 20 ) NOT NULL DEFAULT '' COMMENT '昵称',
	`phone` VARCHAR ( 11 ) NOT NULL DEFAULT '' COMMENT '手机号码',
	`password` VARCHAR ( 255 ) NOT NULL DEFAULT '' COMMENT '密码',
	`email` VARCHAR ( 100 ) NOT NULL DEFAULT '' COMMENT '邮箱',
	`status` TINYINT ( 2 ) NOT NULL DEFAULT '1' COMMENT '用户状态:0-正常,1-冻结,2-注销',
	`create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	`update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
	PRIMARY KEY ( `id` ) ,
	UNIQUE KEY `idx_phone` (`phone`) COMMENT '手机号码唯一索引'
) ENGINE = INNODB DEFAULT CHARSET = utf8mb4 COMMENT '用户表';

CREATE TABLE `ec_product` (
	`id` INT ( 11 ) NOT NULL AUTO_INCREMENT,
	`name` VARCHAR ( 50 ) NOT NULL DEFAULT '' COMMENT '商品名称',
	`serial_number` VARCHAR ( 100 ) NOT NULL DEFAULT '' COMMENT '商品编号',
	`price` DECIMAL ( 10, 2 ) NOT NULL DEFAULT '0.0' COMMENT '商品价格',
	`status` TINYINT ( 2 ) NOT NULL DEFAULT '1' COMMENT '商品状态:0-已下架,1-上架中',
	`distribution` VARCHAR ( 500 ) NOT NULL DEFAULT '' COMMENT '商品描述',
	`image` VARCHAR ( 500 ) NOT NULL DEFAULT '' COMMENT '商品图片地址,多个地址英文逗号隔开',
	`create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	`update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
PRIMARY KEY ( `id` )
) ENGINE = INNODB DEFAULT CHARSET = utf8mb4 COMMENT '商品表';

CREATE TABLE `ec_order` (
	`id` INT ( 11 ) NOT NULL AUTO_INCREMENT,
	`price` DECIMAL ( 10, 2 ) NOT NULL DEFAULT '0.0' COMMENT '商品价格',
	`status` TINYINT ( 2 ) NOT NULL DEFAULT '1' COMMENT '订单状态:0-已取消,1-正常,2-已完成',
	`distribution` VARCHAR ( 500 ) NOT NULL DEFAULT '' COMMENT '订单描述',
	`create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	`update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
PRIMARY KEY ( `id` )
) ENGINE = INNODB DEFAULT CHARSET = utf8mb4 COMMENT '订单表';

CREATE TABLE `ec_order_product` (
	`id` INT ( 11 ) NOT NULL AUTO_INCREMENT,
	`order_id` INT ( 11 ) NOT NULL DEFAULT '' COMMENT '订单id',
	`product_id` INT ( 11 ) NOT NULL DEFAULT '' COMMENT '商品id',
	`amount` INT ( 11 ) NOT NULL DEFAULT '' COMMENT '商品下单数量',
	`create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	`update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
PRIMARY KEY ( `id` )
) ENGINE = INNODB DEFAULT CHARSET = utf8mb4 COMMENT '订单商品关联表';